# Generated by Django 5.2.8 on 2025-11-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_reports', '0003_diseasereport_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertrecommendation',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expertrecommendation',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
    ]
